spring:
  datasource:
    password: docker
    url: jdbc:mysql://mysql-docker:3306/netdeal?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
  flyway:
    locations: classpath:db/migration/mysql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
